version: "3.9"
services:
  db:
    image: postgres:15
    container_name: flowboard_postgres
    restart: always
    environment:
      POSTGRES_USER: flowboard
      POSTGRES_PASSWORD: flowboard
      POSTGRES_DB: flowboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
