services:
  db:
    image: postgres:15
    container_name: flowboard_postgres
    restart: always
    environment:
      POSTGRES_USER: flowboard
      POSTGRES_PASSWORD: flowboard
      POSTGRES_DB: flowboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: flowboard_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://flowboard:flowboard@db:5432/flowboard
      PORT: 4000
      NODE_ENV: production
    ports:
      - "4000:4000"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  frontend:
    build: ./frontend
    container_name: flowboard_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:4000

volumes:
  pgdata:
